get_events:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: furbo
    start:
      example: "2026-09-12 19:00:00"
      selector:
        datetime:
    end:
      example: "2026-09-13 07:00:00"
      selector:
        datetime:
    device_ids:
      selector:
        text:
          multiple: true
    event_names:
      selector:
        select:
          multiple: true
          custom_value: false
          options:
            - Barking
            - ContinuousBarking
            - Crying
            - ContinuousCrying
            - Howling
            - ContinuousHowling
            - PersonDetection
            - DogMoveAbove10Sec
            - Run
            - Selfie
            - EatDrink
            - Chew
            - PeePoo
            - ContinuousPeePoo
            - Vomit
            - ContinuousVomit
            - Seizure
            - ContinuousSeizure
            - GlassBreaking
            - HomeEmergency
            - FurboOnOff
    limit:
      default: 200
      selector:
        number:
          min: 1
          max: 1000
          mode: box

get_insight_report:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: furbo
    dates:
      required: true
      example: "2026-09-12"
      selector:
        text:
          multiple: true
