get_events:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: furbo
    start:
      example: "2026-09-12 19:00:00"
      selector:
        datetime:
    end:
      example: "2026-09-13 07:00:00"
      selector:
        datetime:
    device_ids:
      selector:
        text:
          multiple: true
    event_names:
      selector:
        select:
          multiple: true
          custom_value: false
          options:
            - PersonDetection
            - GlassBreaking
            - Earthquake
            - HomeEmergency
            - AutoCalm
            - Barking
            - ContinuousBarking
            - Crying
            - ContinuousCrying
            - Howling
            - ContinuousHowling
            - Selfie
            - DogMoveAbove10Sec
            - Vomit
            - ContinuousVomit
            - Meowing
            - ContinuousMeowing
            - CatCrying
            - ContinuousCatCrying
            - CatSelfie
            - CatActivity
            - CatVomit
            - ContinuousCatVomit
            - Fighting
    limit:
      default: 200
      selector:
        number:
          min: 1
          max: 1000
          mode: box

get_insight_report:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: furbo
    dates:
      required: true
      example: "2026-09-12"
      selector:
        text:
          multiple: true
